[package]
name = "day-24"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mathru = "0.15.3"
regex = "1.10.2"
z3 = { version = "0.12", features = ["static-link-z3"] }
